# syntax=docker/dockerfile:1

FROM golang:1.16-alpine

WORKDIR /app

#COPY /src/go.mod /
COPY go.mod /

RUN go mod download

#COPY /src ./
COPY . ./

RUN go build -o /product-api

CMD [ "/product-api" ]